name: 'Flyway Migrate'
 
on:
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: List files in github workspace
        run: ls -R /github/workspace

      - name: Run Flyway Migrate
        uses: docker://redgate/flyway:10
        with:
          args: >-
            migrate
            -workingDirectory="/github/workspace/"
            -url="jdbc:sqlserver://sqldocker.database.windows.net:1433;databaseName=SQLDocker_QA;encrypt=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;trustServerCertificate=false"
            -user="redgate@sqldocker"
            -password="Redg@te1"
