name: 'Flyway Migrate'
 
on:
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository into /github/workspace
      - name: Check out repository
        uses: actions/checkout@v2

      # Run Flyway Migrate specifying the migrations folder explicitly
      - name: Run Flyway Migrate
        uses: docker://redgate/flyway:latest
        with:
          args: >-
            migrate
            -locations=filesystem:/github/workspace/migrations
            -url="jdbc:sqlserver://sqldocker.database.windows.net:1433;databaseName=SQLDocker_QA;encrypt=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;trustServerCertificate=false"
            -user="redgate@sqldocker"
            -password="Redg@te1"
