name: 'Flyway Migrate'
 
on:
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository into /github/workspace
      - name: Check out repository
        uses: actions/checkout@v2

      # List files in the repository to verify
      - name: List files in the working directory
        run: ls -R .

      # Run Flyway Migrate with the working directory set to the migrations folder
      - name: Run Flyway Migrate
        uses: docker://redgate/flyway:10
        working-directory: ${{ github.workspace }}/migrations
        with:
          args: >-
            migrate
            -url="jdbc:sqlserver://sqldocker.database.windows.net:1433;databaseName=SQLDocker_QA;encrypt=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;trustServerCertificate=false"
            -user="redgate@sqldocker"
            -password="Redg@te1"
